
import '../../utils/resources/font_manager.dart';
import '../../utils/resources/values_manager.dart';
import '../../utils/styles/decoration.dart';
import '../../utils/theme/app_colors.dart';
import 'package:flutter/material.dart';
import 'appColors.dart';
import 'app_bar.dart';
import 'text.dart';

final ThemeData lightTheme = ThemeData(
  useMaterial3: true,
  fontFamily: FontConstants.fontFamily,
  appBarTheme: appBarThemeLight,
  primaryTextTheme: const TextTheme(),
  dialogTheme: DialogThemeData(
    backgroundColor: AppColor.cardColor.lightColor,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(kRadius)),
    elevation: 0,
  ),
  textTheme: textThemeLight,
  buttonTheme: const ButtonThemeData(),
  bottomNavigationBarTheme: BottomNavigationBarThemeData(
    backgroundColor: AppColor.bottomNavigationBarColor.lightColor,
    selectedItemColor: AppColor.accentColor.lightColor,
  ),
  popupMenuTheme: PopupMenuThemeData(
    color: Colors.white,
    surfaceTintColor: Colors.transparent,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(kRadius)),
  ),
  chipTheme: ChipThemeData(
    padding: EdgeInsets.zero,
    labelPadding: const EdgeInsets.symmetric(horizontal: 6),
    checkmarkColor: Colors.white,
    backgroundColor: Colors.grey[200],
    selectedColor: Colors.white,
    secondarySelectedColor: Colors.green,
    labelStyle: const TextStyle(color: Colors.black),
    secondaryLabelStyle: const TextStyle(color: Colors.white),
    side: const BorderSide(color: Colors.transparent),
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
  ),
  // menuButtonTheme: MenuButtonThemeData(
  //   style: ButtonStyle(
  //     backgroundColor: MaterialStateProperty.all(AppColor.scaffoldBackgroundColor).lightColor,
  //     shape: MaterialStateProperty.all(RoundedRectangleBorder(
  //       borderRadius: BorderRadius.circular(kRadius),
  //     )),
  //   ),
  // ),

  hintColor: AppColor.textSecondaryDark.lightColor,
  brightness: Brightness.light,
  primaryColor: AppCustomColors.appPrimaryColor,
  visualDensity: VisualDensity.adaptivePlatformDensity,
  scaffoldBackgroundColor: AppCustomColors.appWhiteColor,
  listTileTheme: ListTileThemeData(
    iconColor: AppColor.primaryColor.lightColor,
  ),
  cardTheme: CardThemeData(
    clipBehavior: Clip.antiAliasWithSaveLayer,
    color: AppColor.cardColor.lightColor,
    shadowColor: Colors.grey[200],
    surfaceTintColor: Colors.grey.shade50,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(kRadius)),
  ),

  primaryColorDark: AppColor.primaryColorDark.lightColor,
  primaryColorLight: AppColor.primaryColorLight.lightColor,
  dividerTheme: DividerThemeData(color: Colors.grey[200]),
  inputDecorationTheme: kInputDecorationTheme,
  iconTheme: IconThemeData(color: AppColor.iconsColor.lightColor),

  splashColor: Colors.transparent,
  highlightColor: Colors.transparent,
  colorScheme: ColorScheme(
    brightness: Brightness.light,
    primary: AppCustomColors.appPrimaryColor,
    onPrimary: AppColor.scaffoldBackgroundColor.lightColor,
    primaryContainer: AppColor.primaryColor.lightColor,
    onPrimaryContainer: AppColor.scaffoldBackgroundColor.lightColor,
    inversePrimary: AppColor.primaryColor.lightColor,
    surface: AppColor.scaffoldBackgroundColor.lightColor,
    onSurface: AppColor.primaryColor.lightColor,
    inverseSurface: AppColor.scaffoldBackgroundColor.lightColor,
    onInverseSurface: AppColor.primaryColor.lightColor,
    surfaceVariant: AppColor.scaffoldBackgroundColor.lightColor,
    onSurfaceVariant: AppColor.primaryColor.lightColor,
    secondary: AppColor.accentColor.lightColor,
    onSecondary: AppColor.scaffoldBackgroundColor.lightColor,
    secondaryContainer: AppColor.primaryColorDark.lightColor,
    onSecondaryContainer: AppColor.scaffoldBackgroundColor.lightColor,
    background: AppColor.scaffoldBackgroundColor.lightColor,
    onBackground: AppColor.primaryColor.lightColor,
    error: AppColor.errorColor.lightColor,
    onError: AppColor.scaffoldBackgroundColor.lightColor,
    errorContainer: AppColor.errorColor.lightColor,
    onErrorContainer: AppColor.scaffoldBackgroundColor.lightColor,
    tertiary: AppColor.primaryColor.lightColor,
    onTertiary: AppColor.scaffoldBackgroundColor.lightColor,
    tertiaryContainer: AppColor.primaryColor.lightColor,
    onTertiaryContainer: AppColor.scaffoldBackgroundColor.lightColor,
    shadow: AppColor.primaryColor.lightColor,
    outline: AppColor.primaryColor.lightColor,
  ),
  pageTransitionsTheme: const PageTransitionsTheme(builders: {
    TargetPlatform.android: ZoomPageTransitionsBuilder(),
    TargetPlatform.iOS: ZoomPageTransitionsBuilder(),
    TargetPlatform.fuchsia: ZoomPageTransitionsBuilder(),
  }),
);

final ThemeData darkTheme = ThemeData(
  useMaterial3: true,
  primaryColor: AppColor.primaryColor.darkColor,
  fontFamily: FontConstants.fontFamily,
  appBarTheme: appBarThemeDark,
  primaryTextTheme: const TextTheme(),
  buttonTheme: const ButtonThemeData(),
  textTheme: textThemeDark,
  bottomNavigationBarTheme: BottomNavigationBarThemeData(
    backgroundColor: AppColor.bottomNavigationBarColor.darkColor,
    selectedItemColor: AppColor.accentColor.darkColor,
  ),
  hintColor: AppColor.textSecondaryDark.darkColor,
  brightness: Brightness.dark,
  visualDensity: VisualDensity.adaptivePlatformDensity,
  scaffoldBackgroundColor: AppColor.scaffoldBackgroundColor.darkColor,
  cardColor: AppColor.cardColor.darkColor,
  cardTheme: CardThemeData(
    clipBehavior: Clip.antiAliasWithSaveLayer,
    color: AppColor.cardColor.darkColor,
    shadowColor: Colors.grey[200],
    surfaceTintColor: AppColor.surfaceTintColor.darkColor,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(kRadius)),
  ),
  splashColor: Colors.transparent,
  highlightColor: Colors.transparent,
  primaryColorDark: AppColor.primaryColorDark.darkColor,
  primaryColorLight: AppColor.primaryColorLight.darkColor,
  dividerTheme: const DividerThemeData(color: Colors.grey),
  inputDecorationTheme: const InputDecorationTheme(),
  iconTheme: IconThemeData(color: AppColor.iconsColor.darkColor),
  colorScheme: ColorScheme(
    brightness: Brightness.dark,
    primary: AppColor.primaryColor.darkColor,
    onPrimary: AppColor.scaffoldBackgroundColor.darkColor,
    primaryContainer: AppColor.primaryColor.darkColor,
    onPrimaryContainer: AppColor.scaffoldBackgroundColor.darkColor,
    inversePrimary: AppColor.primaryColor.darkColor,
    surface: AppColor.scaffoldBackgroundColor.darkColor,
    onSurface: AppColor.primaryColor.darkColor,
    inverseSurface: AppColor.scaffoldBackgroundColor.darkColor,
    onInverseSurface: AppColor.primaryColor.darkColor,
    surfaceVariant: AppColor.scaffoldBackgroundColor.darkColor,
    onSurfaceVariant: AppColor.primaryColor.darkColor,
    secondary: AppColor.accentColor.darkColor,
    onSecondary: AppColor.scaffoldBackgroundColor.darkColor,
    secondaryContainer: AppColor.primaryColorDark.darkColor,
    onSecondaryContainer: AppColor.scaffoldBackgroundColor.darkColor,
    background: AppColor.scaffoldBackgroundColor.darkColor,
    onBackground: AppColor.primaryColor.darkColor,
    error: AppColor.errorColor.darkColor,
    onError: AppColor.scaffoldBackgroundColor.darkColor,
    errorContainer: AppColor.errorColor.darkColor,
    onErrorContainer: AppColor.scaffoldBackgroundColor.darkColor,
    tertiary: AppColor.primaryColor.darkColor,
    onTertiary: AppColor.scaffoldBackgroundColor.darkColor,
    tertiaryContainer: AppColor.primaryColor.darkColor,
    onTertiaryContainer: AppColor.scaffoldBackgroundColor.darkColor,
    shadow: AppColor.primaryColor.darkColor,
    outline: AppColor.primaryColor.darkColor,
  ),
  pageTransitionsTheme: const PageTransitionsTheme(builders: {
    TargetPlatform.android: ZoomPageTransitionsBuilder(),
    TargetPlatform.iOS: ZoomPageTransitionsBuilder(),
    TargetPlatform.fuchsia: ZoomPageTransitionsBuilder(),
  }),
);
